Add DNS settings for community requests
safing/docs pull request #41
Opened 2021-05-28 15:38 UTC by davegson

implements https://github.com/safing/portmaster/issues/246

2021-05-28 16:17 UTC, dhaavi requested changes
Very nice!

- A couple minor issues.
- NextDNS needs a bit more fixing.

Also, the port 853 is the default for DoT servers, so you may omit it.
See https://github.com/safing/portmaster/blob/82a7350f9afee91f9948912857bbf943969f9b81/resolver/resolvers.go#L108-L109

2021-05-28 16:17 UTC, dhaavi commented on portmaster/guides/dns-configuration.md
> +Needs are different, that is why we list settings suggested by the community down below. Is something missing or out of date? [Make a report](https://github.com/safing/docs/issues/new?assignees=&labe
Missing dot at the end.

2021-05-28 16:17 UTC, dhaavi commented on portmaster/guides/dns-configuration.md
> +🇫🇮 dot://95.216.212.177:853?verify=dot-fi.blahdns.com&name=BlahDNSfi&blockedif=empty
Flags are nice, but no one has usually memorized them all.

While you'd normally only need your own or near to you country's flag, maybe adding the name somehow might be nice. Can we add an alt tag to the flag?

2021-05-28 16:17 UTC, dhaavi commented on portmaster/guides/dns-configuration.md
> +dot://45.90.30.108:853?verify=b4ba5f.dns.nextdns.io&name=NextDNS&blockedif=empty
Everyone has to add their own username here! So we cant just do it like this.

I would more or less copy/paste the instructions from the GH issue.

2021-05-28 16:17 UTC, dhaavi commented on portmaster/guides/dns-configuration.md
> +dot://116.202.176.26:853?verify=dot.libredns.gr&name=LibreDNS&blockedif=empty
I would bet they also use a zero IP for blocking here too.

2021-05-28 16:17 UTC, dhaavi commented on portmaster/guides/dns-configuration.md
> +🇫🇮 dot://95.216.212.177:853?verify=dot-fi.blahdns.com&name=BlahDNSfi&blockedif=empty
From my tests they use block with `zeroip`.

2021-05-31 14:07 UTC, davegson commented
thanks, implemented everything as suggested

2021-05-31 14:07 UTC, merged